#!/usr/bin/env bash
set -e

# Go to the parent directory of where this script is
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )/.." && pwd )"
cd $DIR

# Remove the old keys
rm -rf 01-ssh-keypair/keys/*

# Generate a new keypair
ssh-keygen \
  -b 4096 \
  -f 01-ssh-keypair/keys/terraform-tutorial \
  -t rsa \
  -N "" \
  -C training@hashicorp.com
