#!/usr/bin/env bash
set -e

# Go to the parent directory of where this script is
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )/.." && pwd )"
cd $DIR

# Remove the old keys
rm -rf keys/
mkdir keys

# Generate a new keypair
ssh-keygen \
  -b 4096 \
  -f keys/hashicorp-training \
  -t rsa \
  -N "" \
  -C training@hashicorp.com

# Copy the keypair into our sub-folders
# Copy all the root terraform files into each tutorial
for d in *; do
  if [ ! -d "$d" ]; then
    continue
  fi

  if [ "$d" != "keys" ] && [ "$d" != "scripts" ] && [ "$d" != "shared" ]; then
    rm -rf "$d/keys"
    mkdir "$d/keys"

    for f in keys/hashicorp-training*; do
      echo "Copying $f into $d/keys"
      cp "$f" "$d/keys/"
    done
  fi
done
